### ISSUE TITLE
[REFACTOR] Booking 테이블 분리에 대한 의견을 나눈다.

### ISSUE THREAD

**Issue by semi-cloud** [SOM-Carefully/backend#73]
## 리팩토링 내용

>  현재 서비스 테이블에 서비스 종류(주거/교통/통신/교육)에 따른 모든 컬럼들을 하나의 테이블에 넣었는데, 분리하는게 좋은가?

#### 현재 테이블 구조

<img alt="image" src="https://user-images.githubusercontent.com/71436576/215112579-7b85cfe5-71dd-400e-be9e-9b591be8a33a.png" width=50% height=50%>

**Comment by myunbongs** [comment]
아고 제가 이슈로 열 걸 그랬네욥 헤헷 감삼다!

**Comment by semi-cloud** [comment]
제가 찾아봤을때는..!!

**1. 테이블을 분리하지 않는다**
+ 빈 데이터로 인해 공간의 낭비가 존재한다.
+ 컬럼 수가 많아지면 여러 블럭에 넓게 분포가 되기 때문에 I/O가 증가한다(DB 입출력 단위인 블럭 사이즈는 건드리지 않는게 좋음)
 [컬럼수가 많은 테이블의 1:1 분리를 통한 성능 향상](http://www.gurubee.net/lecture/4254)
+ `Row Chaining`, `Row migration` 현상이 일어난다. [[Oracle] Row chaining, Row migration 현상 이해하기](https://m.blog.naver.com/itperson/220881585033)
 
 **2. 테이블을 분리한다.**
 + 조인 비용이 증가한다.

함수 종속성 생각하면은 정규화하는게 좋을 것 같긴 한데 지금 컬럼 개수가 10개정도 밖에 안돼서 고민이 되네요..😢

**Comment by semi-cloud** [comment]
근데 2번과 같은 경우 제가 생각하기에는 어짜피 `BookingRequest` 테이블에 주거/교육/통신/교통 클래스 필드가 들어가야 할테고
해당되는 서비스 하나 빼고는 `null` 값이 들어가는거는 어쩔 수 없을 것 같아요..

비는 데이터 공간 없이 처리할 수 있는 방법이 있을까요!?

**Comment by myunbongs** [comment]
저는 ㅋㅋ ㅋ 프로젝트 시작부터 했던 고민이라... 친구들한테 물어봤을 때 아직 데이터도 그렇구 컬럼도 적으니까 단일 테이블로 두는게 좋을 것 같다구 해서 그렇게 구현했던 거라 DB 보다가 널값 신경쓰여서 함 말씀드려봤어요! 그냥 둬두 될 것 같기도 하구.. 

비는 데이터 공간 없이 구현하는 건 카카오톡에서 말씀드렸던 것처럼  그냥 서비스 종류 별로 테이블 하나씩 만드는 거욥 ㅠ ㅠ

>  해당되는 서비스 하나 빼고는 null 값이 들어가는거는 어쩔 수 없을 것 같아요..

고민을 좀 더 해봐야겠어요 🥲

**Comment by semi-cloud** [comment]
종류별로 만들어도 어짜피 `BookingRequest` 테이블이랑 연결 해줘야 하니까 빈 공간이 생기지 않나요!? 이해가 안되서 ʘ̥_ʘ

**Comment by myunbongs** [comment]
> 종류별로 만들어도 어짜피 `BookingRequest` 테이블이랑 연결 해줘야 하니까 빈 공간이 생기지 않나요!? 이해가 안되서 ʘ̥_ʘ

롸 추가해서 수정하고 있었어요!

**Comment by semi-cloud** [comment]
근데 저도 단일 테이블로 그냥 가도 좋을 것 같아요!!!
여기 링크 보시면 컬럼 40개까지는 괜찮다고 하더라구요 [MySQL 컬럼수 증가에 따른 이슈](https://dung-beetle.tistory.com/53)

**Comment by myunbongs** [comment]
> 근데 저도 단일 테이블로 그냥 가도 좋을 것 같아요!!! 여기 링크 보시면 컬럼 40개까지는 괜찮다고 하더라구요 [MySQL 컬럼수 증가에 따른 이슈](https://dung-beetle.tistory.com/53)

역시 스프링 천재 셈....... 💕
